### no auth header -> 401
GET http://localhost:3000/api/admin/users


Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IkJjN05jZUVyOEhkT1hNNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2tsZmd1YWV5d3NsZ3VyY25jaGpuLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwNTdiZTczMS0zNjNjLTRkNmQtYjJlOC1lZmE4YTI5OThmNTkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzcwMDMzMjE4LCJpYXQiOjE3NzAwMjk2MTgsImVtYWlsIjoicXVzd2hkZGJzODVAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NzAwMjk2MTh9XSwic2Vzc2lvbl9pZCI6ImQzODkxZjA3LTZmMDktNDZiMS1iZjM3LWNmNTkxZTExNmRmMSIsImlzX2Fub255bW91cyI6ZmFsc2V9.S-ObVXy3DT1Ovcvmrkcoafl1xiZWuVa1C2SlPJ1xAnE




#Ctrl + Alt + R





#{
 # "email": "user1@aaa.com",
 # "accessToken": "eyJhbGciOiJIUzI1NiIsImtpZCI6IkJjN05jZUVyOEhkT1hNNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2tsZmd1YWV5d3NsZ3VyY25jaGpuLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjY2Q1MjM0NC0yYzBhLTRiYzUtYTc3MS1jMjZkNzhiNmVjZWMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY4ODIyNjM0LCJpYXQiOjE3Njg4MTkwMzQsImVtYWlsIjoidXNlcjFAYWFhLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzY4ODE5MDM0fV0sInNlc3Npb25faWQiOiI1YTMxMTI1MS03NWJlLTRmMDQtODFjNS0zNjk5ZTJhM2RhNDQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.VFXXkmq3r1iPXndVj4Ji2dUDKtBEvFdFTTQaEygyme4",
 # "refreshToken": "3npvcaepsvkn"
#}


